name = "Additive"
author = "SkywardMC"
version = "1.34.0+1.21.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "571f9469d653fc4069f1edbb06cea668acafb1877d64333889340603cc27191b"

[versions]
fabric = "0.16.10"
minecraft = "1.21.1"
