name = "Additive"
author = "SkywardMC"
version = "1.34.0+1.21.3.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "793e32689651f867fe3c88d22cd69fe528af3d34ddcc07939dc86e389799afa9"

[versions]
fabric = "0.16.10"
minecraft = "1.21.3"
