name = "Additive"
author = "SkywardMC"
version = "1.34.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1046f95f9ad2cacf06abbc19138a00eb6561d1538e4031c48624fb6bd8f95905"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
