name = "Additive"
author = "SkywardMC"
version = "1.33.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a2bdc382f1b9188fd0feb35676980a20074dc1c0aa37b56e0861030427f46e9"

[versions]
fabric = "0.16.10"
minecraft = "1.21.4"
