name = "Additive"
author = "SkywardMC"
version = "1.31.0+1.21.4.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc800789993e033aa0de4f5761aeb7a325cd34cdc030d4d1e68b6536d14f512e"

[versions]
fabric = "0.16.9"
minecraft = "1.21.4"
