name = "Additive"
author = "SkywardMC"
version = "1.32.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77cdf349f63595b5f7f55867ba38fbab13bb0790c461ae0dda410fe09657a095"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
