name = "Additive"
author = "SkywardMC"
version = "1.33.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ab8ac58a7c412fbbf659c20a66f9477f845f988578f2012a340b27cefdd89ae"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
