name = "Additive"
author = "SkywardMC"
version = "1.34.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03da01194feadd497b7ca9d276df52f781916b657a7582a368881815822c6870"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
