name = "Additive"
author = "SkywardMC"
version = "1.33.0+1.20.1.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3aafc06b84ad51057534aa1f3fd767e7cf70562a471c536c91a473515953a5ba"

[versions]
fabric = "0.16.10"
minecraft = "1.20.1"
